steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/tactical-drops-app', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/tactical-drops-app']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'tactical-drops'
      - '--image'
      - 'gcr.io/$PROJECT_ID/tactical-drops-app'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - '$PROJECT_ID:us-central1:tactical-drops-db'
      - '--set-secrets'
      - 'DATABASE_URL=database-url:latest,SESSION_SECRET=session-secret:latest,SQUARE_APPLICATION_ID=square-application-id:latest,SQUARE_LOCATION_ID=square-location-id:latest'

images:
  - 'gcr.io/$PROJECT_ID/tactical-drops-app'

timeout: '1800s' 