steps:
  # Build and push using Cloud Native Buildpacks
  - name: 'gcr.io/k8s-skaffold/pack'
    entrypoint: 'pack'
    args:
      - 'build'
      - 'gcr.io/$PROJECT_ID/tactical-drops'
      - '--builder=gcr.io/buildpacks/builder:v1'
      - '--publish'
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'tactical-drops'
      - '--image'
      - 'gcr.io/$PROJECT_ID/tactical-drops'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - '$PROJECT_ID:us-central1:tactical-drops-db'
      - '--set-secrets'
      - 'DATABASE_URL=database-url:latest,SESSION_SECRET=session-secret:latest,SQUARE_APPLICATION_ID=square-application-id:latest,SQUARE_LOCATION_ID=square-location-id:latest'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/$PROJECT_ID/tactical-drops'

timeout: '1800s' 